name: CELLO_downstream

channels:
  - conda-forge
  - bioconda

dependencies:
  # Reverse complement reads
  - seqkit=2.14.0

  # Mapping reads
  - winnowmap=2.03

  # Long-read transcriptomics
  - flair=3.0.1

  # BED operations
  - bedtools=2.31.1

  #SQUANTI3
  - sqanti3=6.0.1
